FROM kcs-reasonable-configs-install-ev

COPY . .

COPY .zshrc /root/
COPY .zshrc /home/arch/

COPY ./etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist

# CMD echo -e "$testInput" | source ./Install.sh && umount -lf /mnt &> /dev/null && exit;
