-- ──────────────── HYPRLAND ENTRY POINT ────────────────
-- Replaces hyprland.conf with Lua modules loaded via require()
-- nwg-displays monitors/workspaces are imported if they exist,
-- otherwise falls back to custom defaults.

-- ═══ Color vars (generated by castle-shell/theme-checker.service) ═══
local colorsPath = os.getenv("HOME") .. "/.config/castle-shell/hypr-colors"
_G.colors        = require(colorsPath)  -- expose globally for cross-module use

-- ═══ Global vim motions shortcuts (optional, may not exist) ═══
local vimShortcuts = os.getenv("HOME") .. "/.config/castle-shell/global-vim-motions/shortcuts"
if pcall(require, vimShortcuts) then  -- no-op if file doesn't exist yet
    print("[hyprland.lua] Vim shortcuts loaded.")
else
    print("[hyprland.lua] Vim shortcuts not found — skipping.")
end

-- ═══ Monitors (nwg-displays generated OR fallback defaults) ═══
local monitorsNwg = os.getenv("HOME") .. "/.config/hypr/monitors"
local fallbackMonitors = os.getenv("HOME") .. "/.config/hypr/custom/monitors"

if pcall(require, monitorsNwg) then
    print("[hyprland.lua] nwg-displays monitors loaded.")
else
    -- nwg hasn't generated files yet → use custom defaults until first boot completes
    if pcall(require, fallbackMonitors) then
        print("[hyprland.lua] Fallback monitor config loaded (nwg not ready).")
    else
        warn("[hyprland.lua] No monitor config available — using Hyprland auto-detect.")
    end
end

-- ═══ Workspaces (nwg-displays generated OR skip) ═══
local workspacesNwg = os.getenv("HOME") .. "/.config/hypr/workspaces"
if pcall(require, workspacesNwg) then
    print("[hyprland.lua] nwg-displays workspaces loaded.")
else
    warn("[hyprland.lua] No workspace config available — using Hyprland defaults.")
end

-- ═══ Custom settings modules (loaded in sequence) ═══
local custom = os.getenv("HOME") .. "/.config/hypr/custom"

require(custom .. "/settings")      -- variables + general/input/misc
require(custom .. "/keybindings")   -- all keybinds (uses _G vars from settings)
require(custom .. "/autostart")     -- start services/programs last
require(custom .. "/looks")         -- decoration, animations, plugin looks  
require(custom .. "/plugins")       -- load and configure plugins
require(custom .. "/windowrules")   -- window rules 
