-- Generated by nwg-displays on 2026-09-11 at 22:02:13. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@120.0",
    position = "640x720",
    scale = 1.4999999999999996,
    vrr = 0
})
hl.monitor({
    output = "DP-2",
    mode = "2560x1440@60.0",
    position = "1920x131",
    scale = 1.1,
    vrr = 0
})
